server:
  port: 8080
  servlet:
    session:
      cookie:
        name: IAMSESSION
        http-only: true
        same-site: lax

spring:
  datasource:
    url: ${IAM_DB_URL:jdbc:mysql://127.0.0.1:3306/iam_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    username: ${IAM_DB_USERNAME:root}
    password: ${IAM_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai
  jackson:
    time-zone: Asia/Shanghai

logging:
  level:
    org.springframework.security: INFO

app:
  security:
    issuer: http://127.0.0.1:8080
